using System.Text;

namespace Bahyway.SharedKernel.Compiler
{
    public class AkkadianGenerator
    {
        public GenerationResult Generate(AkkadianModel model)
        {
            var result = new GenerationResult();
            var sqlBuilder = new StringBuilder();
            var cypherBuilder = new StringBuilder();

            // 1. Header
            sqlBuilder.AppendLine($"-- Generated by Akkadian Compiler for Context: {model.Context?.Name}");
            sqlBuilder.AppendLine("CREATE EXTENSION IF NOT EXISTS age;");
            sqlBuilder.AppendLine("LOAD 'age';");
            sqlBuilder.AppendLine($"SELECT create_graph('{model.Context?.Name.ToLower()}_graph');");
            sqlBuilder.AppendLine();

            foreach (var concept in model.Concepts)
            {
                // ---------------------------------------------------------
                // A. Generate Data Vault Tables (Relational Truth)
                // ---------------------------------------------------------

                // 1. The Hub (Identity)
                string hubName = $"Hub_{concept.Name}";
                sqlBuilder.AppendLine($"-- HUB for {concept.Name}");
                sqlBuilder.AppendLine($"CREATE TABLE \"{hubName}\" (");
                sqlBuilder.AppendLine($"    \"{concept.Name}Hash\" CHAR(64) PRIMARY KEY,"); // SHA256 Key
                sqlBuilder.AppendLine($"    \"VisualID\" VARCHAR(50) NOT NULL,");           // The RGB Key
                sqlBuilder.AppendLine($"    \"LoadDate\" TIMESTAMP DEFAULT NOW(),");
                sqlBuilder.AppendLine($"    \"RecordSource\" VARCHAR(100)");
                sqlBuilder.AppendLine(");");
                sqlBuilder.AppendLine();

                // 2. The Satellite (Properties/Attributes)
                if (concept.Properties.Count > 0)
                {
                    string satName = $"Sat_{concept.Name}_Attributes";
                    sqlBuilder.AppendLine($"-- SATELLITE for {concept.Name}");
                    sqlBuilder.AppendLine($"CREATE TABLE \"{satName}\" (");
                    sqlBuilder.AppendLine($"    \"{concept.Name}Hash\" CHAR(64) REFERENCES \"{hubName}\"(\"{concept.Name}Hash\"),");
                    sqlBuilder.AppendLine($"    \"LoadDate\" TIMESTAMP DEFAULT NOW(),");

                    // Generate a column for every property defined in DSL
                    foreach (var prop in concept.Properties)
                    {
                        sqlBuilder.AppendLine($"    \"{prop.Name}\" TEXT,");
                    }

                    sqlBuilder.AppendLine($"    \"HashDiff\" CHAR(64)");
                    sqlBuilder.AppendLine(");");
                    sqlBuilder.AppendLine();
                }

                // ---------------------------------------------------------
                // B. Generate Apache AGE Cypher (Semantic Topology)
                // ---------------------------------------------------------
                // Generates a "Label" creation command for the Graph
                cypherBuilder.AppendLine($"-- Node Definition for {concept.Name}");
                cypherBuilder.AppendLine($"SELECT * FROM cypher('{model.Context?.Name.ToLower()}_graph', $$");
                cypherBuilder.AppendLine($"    CREATE (:{concept.Name} {{ _type: 'Concept' }})");
                cypherBuilder.AppendLine("$$) as (n agtype);");
            }

            result.SqlScript = sqlBuilder.ToString();
            result.CypherScript = cypherBuilder.ToString();

            return result;
        }
    }
}