-- =============================================
-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)
-- Generated by Akkadian.Compiler v3.0
-- =============================================

-- CONTEXT: beeMDM_Knowledge
CREATE SCHEMA IF NOT EXISTS beeMDM_Knowledge;

