-- =============================================
-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)
-- Generated by Akkadian.Compiler v3.1
-- =============================================

-- CONTEXT: WPDWay_Optimized
CREATE SCHEMA IF NOT EXISTS WPDWay_Optimized;

-- HUB: hub_pipe_segment
CREATE TABLE IF NOT EXISTS WPDWay_Optimized.hub_pipe_segment (
    color_id BIGINT PRIMARY KEY NOT NULL,
    segment_uuid UUID UNIQUE,
    material VARCHAR(50),
    diameter_mm INTEGER,
    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL,
    RecordSource VARCHAR(100) NOT NULL
);
-- Optimization: Clustering by color_id
CREATE INDEX IF NOT EXISTS idx_hub_pipe_segment_cluster ON WPDWay_Optimized.hub_pipe_segment USING BRIN (color_id);
CLUSTER WPDWay_Optimized.hub_pipe_segment USING idx_hub_pipe_segment_cluster;


-- LINK: link_pipe_connection
CREATE TABLE IF NOT EXISTS WPDWay_Optimized.link_pipe_connection (
    upstream_color_id BIGINT,
    downstream_color_id BIGINT,
    connection_type VARCHAR(20),
    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL,
    RecordSource VARCHAR(100) NOT NULL
);
-- Optimization: Clustering by upstream_color_id
CREATE INDEX IF NOT EXISTS idx_link_pipe_connection_cluster ON WPDWay_Optimized.link_pipe_connection USING BRIN (upstream_color_id);
CLUSTER WPDWay_Optimized.link_pipe_connection USING idx_link_pipe_connection_cluster;


-- SATELLITE: sat_defect_metrics
CREATE TABLE IF NOT EXISTS WPDWay_Optimized.sat_defect_metrics (
    color_id BIGINT,
    wall_thickness DECIMAL(10,2),
    pressure_psi DECIMAL(10,2),
    soil_acidity_ph DECIMAL(5,2),
    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL,
    RecordSource VARCHAR(100) NOT NULL,
    ValidFrom TIMESTAMP DEFAULT NOW() NOT NULL,
    ValidTo TIMESTAMP NULL,
    IsCurrent BOOLEAN DEFAULT TRUE
);


