# =============================================
# AKKADIAN GENERATED AI SERVICE (FastAPI)
# Generated by Akkadian.Compiler v3.0
# =============================================
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from typing import List, Dict

# Initialize App
app = FastAPI(title="Akkadian Vector Service")

print('Loading Model: ...')
model_WPDWay_Optimized = SentenceTransformer('')

class EmbeddingRequest(BaseModel):
    text: str

@app.post('/wpdway_optimized/embed')
async def embed_wpdway_optimized(req: EmbeddingRequest):
    embeddings = model_WPDWay_Optimized.encode(req.text)
    return { 'vector': embeddings.tolist() }

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
