# =============================================
# AKKADIAN GENERATED AI SERVICE (FastAPI)
# Generated by Akkadian.Compiler v3.0
# =============================================
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from typing import List, Dict

# Initialize App
app = FastAPI(title="Akkadian Vector Service")

print('Loading Model: sentence-transformers/all-MiniLM-L6-v2...')
model_beeMDM_Knowledge = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

class EmbeddingRequest(BaseModel):
    text: str

@app.post('/beemdm_knowledge/embed')
async def embed_beemdm_knowledge(req: EmbeddingRequest):
    embeddings = model_beeMDM_Knowledge.encode(req.text)
    return { 'vector': embeddings.tolist() }

# Entity Vectorization: data_asset_profile
class DataAssetProfileRequest(BaseModel):
    asset_name: str
    business_description: str
    technical_schema: str
    data_steward_name: str

@app.post('/beemdm_knowledge/vectorize/data_asset_profile')
async def vectorize_data_asset_profile(req: DataAssetProfileRequest):
    # Strategy: Concatenate fields defined in DSL
    combined_text = req.asset_name + ' ' + req.business_description + ' ' + req.technical_schema + ' ' + req.data_steward_name
    vector = model_beeMDM_Knowledge.encode(combined_text)
    return { 'vector': vector.tolist() }

# Entity Vectorization: governance_policy
class GovernancePolicyRequest(BaseModel):
    policy_name: str
    compliance_text: str
    jurisdiction: str

@app.post('/beemdm_knowledge/vectorize/governance_policy')
async def vectorize_governance_policy(req: GovernancePolicyRequest):
    # Strategy: Concatenate fields defined in DSL
    combined_text = req.policy_name + ' ' + req.compliance_text + ' ' + req.jurisdiction
    vector = model_beeMDM_Knowledge.encode(combined_text)
    return { 'vector': vector.tolist() }

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
