-- =============================================
-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)
-- Generated by Akkadian.Compiler v3.1
-- =============================================

-- CONTEXT: Najaf_Cemetery_Master
CREATE SCHEMA IF NOT EXISTS Najaf_Cemetery_Master;

-- HUB: hub_deceased_record
CREATE TABLE IF NOT EXISTS Najaf_Cemetery_Master.hub_deceased_record (
    tribal_color_id BIGINT PRIMARY KEY NOT NULL,
    civil_id VARCHAR(50) UNIQUE,
    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL,
    RecordSource VARCHAR(100) NOT NULL
);
-- Optimization: Clustering by tribal_color_id
CREATE INDEX IF NOT EXISTS idx_hub_deceased_record_cluster ON Najaf_Cemetery_Master.hub_deceased_record USING BRIN (tribal_color_id);
CLUSTER Najaf_Cemetery_Master.hub_deceased_record USING idx_hub_deceased_record_cluster;


-- SATELLITE: sat_burial_info
CREATE TABLE IF NOT EXISTS Najaf_Cemetery_Master.sat_burial_info (
    tribal_color_id BIGINT,
    death_date DATE,
    burial_date DATE,
    death_certificate_img VARCHAR(500),
    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL,
    RecordSource VARCHAR(100) NOT NULL,
    ValidFrom TIMESTAMP DEFAULT NOW() NOT NULL,
    ValidTo TIMESTAMP NULL,
    IsCurrent BOOLEAN DEFAULT TRUE
);


