using System.Text;
using System.Collections.Generic;
using Bahyway.SharedKernel.Graph; // Assumes this is where VisualNode/GraphTopology lives
using System;
using System.Linq;

namespace Bahyway.KGEditor.UI.Services
{
    public class AkkadianSourceGenerator
    {
        public string GenerateSource(string contextName, GraphTopology graph)
        {
            var sb = new StringBuilder();

            // 1. Header & Context
            sb.AppendLine("// ============================================================");
            sb.AppendLine($"// AUTO-GENERATED BY KGEDITOR - {DateTime.Now}");
            sb.AppendLine("// Visual Model to DSL Transformation");
            sb.AppendLine("// ============================================================");
            sb.AppendLine();
            sb.AppendLine($"CONTEXT {CleanName(contextName)} {{");
            sb.AppendLine();

            // 2. Identity Block (Defaulting to Spatial Color for Scale)
            sb.AppendLine("    // 1. Identity Strategy");
            sb.AppendLine("    IDENTITY AutoGen_Identity {");
            sb.AppendLine("        BUSINESS_KEY: auto_uuid");
            sb.AppendLine("        SPATIAL_ID {");
            sb.AppendLine("            ALGORITHM: EXTENDED_COLOR_64");
            sb.AppendLine("            DIMENSIONS: [layer, x, y]");
            sb.AppendLine("            PRECISION: 64");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 3. Storage Block (The Data Structures)
            sb.AppendLine("    // 2. Physical Storage (Data Vault)");
            sb.AppendLine("    STORAGE DataVault {");

            foreach (var node in graph.Nodes)
            {
                string hubName = $"hub_{CleanName(node.Label)}";

                // We define a Hub for every visual node
                sb.AppendLine($"        HUB: {hubName} WITH CLUSTERED_BY: color_id {{");
                sb.AppendLine($"            color_id: BIGINT PRIMARY KEY,");
                sb.AppendLine($"            global_id: UUID UNIQUE,");
                sb.AppendLine($"            description: VARCHAR(500),");
                // Default BRIN index for performance
                sb.AppendLine($"            INDEXES {{ BRIN: [color_id] }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // 4. Presentation Block (The Visuals - THIS IS THE MAGIC)
            // This ensures that when we reload, the nodes stay where the user put them.
            sb.AppendLine("    // 3. Visual Presentation");
            sb.AppendLine("    PRESENTATION {");

            foreach (var node in graph.Nodes)
            {
                string hubName = $"hub_{CleanName(node.Label)}";

                sb.AppendLine($"        STYLE {hubName} {{");
                sb.AppendLine($"            SHAPE: RECTANGLE");
                // Save the Hex Color the user picked
                sb.AppendLine($"            COLOR: '{node.ColorHex}'");
                sb.AppendLine($"            LABEL: description");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // 5. Basic Vectorization (Ready for AI)
            sb.AppendLine("    // 4. AI Readiness");
            sb.AppendLine("    VECTORIZATION {");
            sb.AppendLine("        MODEL: 'sentence-transformers/all-MiniLM-L6-v2'");
            sb.AppendLine("        EMBEDDINGS {");
            sb.AppendLine("            // Auto-vectorize descriptions for search");
            sb.AppendLine("            node_search: [description]");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}"); // End Context

            return sb.ToString();
        }

        // Helper to ensure names are DSL-safe (no spaces, special chars)
        private string CleanName(string input)
        {
            if (string.IsNullOrEmpty(input)) return "Unknown";
            return input.Replace(" ", "_").Replace("-", "_").Replace(".", "_");
        }
    }
}