using Akkadian.Core.Ast;
using System.Text;

namespace Akkadian.Core.Generators
{
    public class PythonGenerator
    {
        public string Generate(AkkadianProgram program)
        {
            var sb = new StringBuilder();

            // 1. Python Imports & Setup
            sb.AppendLine("# =============================================");
            sb.AppendLine("# AKKADIAN GENERATED AI SERVICE (FastAPI)");
            sb.AppendLine("# Generated by Akkadian.Compiler v3.0");
            sb.AppendLine("# =============================================");
            sb.AppendLine("import uvicorn");
            sb.AppendLine("from fastapi import FastAPI, HTTPException");
            sb.AppendLine("from pydantic import BaseModel");
            sb.AppendLine("from sentence_transformers import SentenceTransformer");
            sb.AppendLine("from typing import List, Dict");
            sb.AppendLine();

            sb.AppendLine("# Initialize App");
            sb.AppendLine("app = FastAPI(title=\"Akkadian Vector Service\")");
            sb.AppendLine();

            // 2. Load Models defined in DSL
            foreach (var context in program.Contexts)
            {
                if (context.Vectorization != null)
                {
                    string modelName = context.Vectorization.ModelName;
                    sb.AppendLine($"print('Loading Model: {modelName}...')");
                    // We generate a global variable for the model
                    sb.AppendLine($"model_{context.Name} = SentenceTransformer('{modelName}')");
                }
            }
            sb.AppendLine();

            // 3. Request DTOs
            sb.AppendLine("class EmbeddingRequest(BaseModel):");
            sb.AppendLine("    text: str");
            sb.AppendLine();

            // 4. Generate Endpoints
            foreach (var context in program.Contexts)
            {
                if (context.Vectorization == null) continue;

                // Generic Embed Endpoint
                sb.AppendLine($"@app.post('/{context.Name.ToLower()}/embed')");
                sb.AppendLine($"async def embed_{context.Name.ToLower()}(req: EmbeddingRequest):");
                sb.AppendLine($"    embeddings = model_{context.Name}.encode(req.text)");
                sb.AppendLine($"    return {{ 'vector': embeddings.tolist() }}");
                sb.AppendLine();

                // Specific Entity Endpoints based on DSL definitions
                foreach (var embeddingDef in context.Vectorization.Embeddings)
                {
                    string entityName = embeddingDef.Key; // e.g., customer_profile
                    var fields = embeddingDef.Value;      // e.g., [name, bio]

                    sb.AppendLine($"# Entity Vectorization: {entityName}");
                    sb.AppendLine($"class {ToPascalCase(entityName)}Request(BaseModel):");
                    foreach (var field in fields)
                    {
                        sb.AppendLine($"    {field}: str");
                    }
                    sb.AppendLine();

                    sb.AppendLine($"@app.post('/{context.Name.ToLower()}/vectorize/{entityName}')");
                    sb.AppendLine($"async def vectorize_{entityName}(req: {ToPascalCase(entityName)}Request):");

                    // Logic to combine fields into one string for embedding
                    string combineLogic = string.Join(" + ' ' + ", fields.Select(f => $"req.{f}"));

                    sb.AppendLine($"    # Strategy: Concatenate fields defined in DSL");
                    sb.AppendLine($"    combined_text = {combineLogic}");
                    sb.AppendLine($"    vector = model_{context.Name}.encode(combined_text)");
                    sb.AppendLine($"    return {{ 'vector': vector.tolist() }}");
                    sb.AppendLine();
                }
            }

            // 5. Main Entry Point
            sb.AppendLine("if __name__ == '__main__':");
            sb.AppendLine("    uvicorn.run(app, host='0.0.0.0', port=8000)");

            return sb.ToString();
        }

        private string ToPascalCase(string text)
        {
            if (string.IsNullOrEmpty(text)) return text;
            var words = text.Split(new[] { '_', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            return string.Join("", words.Select(w => char.ToUpper(w[0]) + w.Substring(1)));
        }
    }
}