using Akkadian.Core.Ast;
using System.Collections.Generic;
using System.Text;

namespace Akkadian.Core.Generators
{
    public class SqlGenerator
    {
        public string Generate(AkkadianProgram program)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- =============================================");
            sb.AppendLine("-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)");
            sb.AppendLine("-- Generated by Akkadian.Compiler v3.0");
            sb.AppendLine("-- =============================================");
            sb.AppendLine();

            foreach (var context in program.Contexts)
            {
                sb.AppendLine($"-- CONTEXT: {context.Name}");
                sb.AppendLine($"CREATE SCHEMA IF NOT EXISTS {context.Name};");
                sb.AppendLine();

                if (context.Storage != null)
                {
                    // Generate Hubs
                    foreach (var hub in context.Storage.Hubs)
                    {
                        sb.AppendLine(GenerateTableScript(context.Name, hub));
                    }

                    // Generate Links
                    foreach (var link in context.Storage.Links)
                    {
                        sb.AppendLine(GenerateTableScript(context.Name, link));
                    }

                    // Generate Satellites
                    foreach (var sat in context.Storage.Satellites)
                    {
                        sb.AppendLine(GenerateTableScript(context.Name, sat));
                    }
                }
            }

            return sb.ToString();
        }

        private string GenerateTableScript(string schema, TableNode table)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"-- {table.Type}: {table.Name}");
            sb.AppendLine($"CREATE TABLE IF NOT EXISTS {schema}.{table.Name} (");

            var lines = new List<string>();

            // 1. Add User Defined Columns
            foreach (var col in table.Columns)
            {
                string line = $"    {col.Name} {MapToPostgresType(col.DataType)}";

                if (col.IsPrimaryKey) line += " PRIMARY KEY";
                else if (col.IsUnique) line += " UNIQUE";

                // NOT NULL is usually good for keys, but let's keep it simple for now
                if (col.IsPrimaryKey) line += " NOT NULL";

                lines.Add(line);
            }

            // 2. Add Standard Data Vault Audit Columns (The Akkadian Pattern)
            lines.Add($"    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL");
            lines.Add($"    RecordSource VARCHAR(100) NOT NULL");

            // 3. Add Temporal Columns (If requested in DSL)
            if (table.HasTemporalTracking)
            {
                lines.Add($"    ValidFrom TIMESTAMP DEFAULT NOW() NOT NULL");
                lines.Add($"    ValidTo TIMESTAMP NULL");
                lines.Add($"    IsCurrent BOOLEAN DEFAULT TRUE");
            }

            sb.AppendLine(string.Join(",\n", lines));
            sb.AppendLine(");");
            sb.AppendLine(); // Empty line after table
            return sb.ToString();
        }

        private string MapToPostgresType(string akkadianType)
        {
            // Maps DSL types to Postgres types
            // Example: VARCHAR(200) -> VARCHAR(200)

            if (akkadianType.StartsWith("VARCHAR")) return akkadianType;
            if (akkadianType.StartsWith("DECIMAL")) return akkadianType;

            return akkadianType switch
            {
                "UUID" => "UUID",
                "INT" => "INTEGER",
                "TIMESTAMP" => "TIMESTAMP",
                _ => akkadianType // Fallback
            };
        }
    }
}