using Akkadian.Core.Ast;
using System.Collections.Generic;
using System.Text;

namespace Akkadian.Core.Generators
{
    public class SqlGenerator
    {
        public string Generate(AkkadianProgram program)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- =============================================");
            sb.AppendLine("-- AKKADIAN GENERATED SQL (PostgreSQL / Data Vault)");
            sb.AppendLine("-- Generated by Akkadian.Compiler v3.1");
            sb.AppendLine("-- =============================================");
            sb.AppendLine();

            foreach (var context in program.Contexts)
            {
                sb.AppendLine($"-- CONTEXT: {context.Name}");
                sb.AppendLine($"CREATE SCHEMA IF NOT EXISTS {context.Name};");
                sb.AppendLine();

                if (context.Storage != null)
                {
                    foreach (var hub in context.Storage.Hubs)
                        sb.AppendLine(GenerateTableScript(context.Name, hub));

                    foreach (var link in context.Storage.Links)
                        sb.AppendLine(GenerateTableScript(context.Name, link));

                    foreach (var sat in context.Storage.Satellites)
                        sb.AppendLine(GenerateTableScript(context.Name, sat));
                }
            }

            return sb.ToString();
        }

        private string GenerateTableScript(string schema, TableNode table)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"-- {table.Type}: {table.Name}");
            sb.AppendLine($"CREATE TABLE IF NOT EXISTS {schema}.{table.Name} (");

            var lines = new List<string>();

            // 1. Columns
            foreach (var col in table.Columns)
            {
                string line = $"    {col.Name} {MapToPostgresType(col.DataType)}";
                if (col.IsPrimaryKey) line += " PRIMARY KEY";
                else if (col.IsUnique) line += " UNIQUE";
                if (col.IsPrimaryKey) line += " NOT NULL";
                lines.Add(line);
            }

            // 2. Audit Columns
            lines.Add($"    LoadDate TIMESTAMP DEFAULT NOW() NOT NULL");
            lines.Add($"    RecordSource VARCHAR(100) NOT NULL");

            // 3. Temporal Columns
            if (table.HasTemporalTracking)
            {
                lines.Add($"    ValidFrom TIMESTAMP DEFAULT NOW() NOT NULL");
                lines.Add($"    ValidTo TIMESTAMP NULL");
                lines.Add($"    IsCurrent BOOLEAN DEFAULT TRUE");
            }

            sb.AppendLine(string.Join(",\n", lines));
            sb.AppendLine(");");

            // 4. Clustering (Physical Ordering) - THIS WAS THE PART CAUSING ERRORS
            if (!string.IsNullOrEmpty(table.ClusteredBy))
            {
                string idxName = $"idx_{table.Name}_cluster";
                sb.AppendLine($"-- Optimization: Clustering by {table.ClusteredBy}");
                sb.AppendLine($"CREATE INDEX IF NOT EXISTS {idxName} ON {schema}.{table.Name} USING BRIN ({table.ClusteredBy});");
                sb.AppendLine($"CLUSTER {schema}.{table.Name} USING {idxName};");
            }

            sb.AppendLine();
            return sb.ToString();
        }

        private string MapToPostgresType(string akkadianType)
        {
            if (akkadianType.StartsWith("VARCHAR")) return akkadianType;
            if (akkadianType.StartsWith("DECIMAL")) return akkadianType;
            if (akkadianType == "BIGINT") return "BIGINT";

            return akkadianType switch
            {
                "UUID" => "UUID",
                "INT" => "INTEGER",
                "TIMESTAMP" => "TIMESTAMP",
                _ => akkadianType
            };
        }
    }
}