-- Generated by Akkadian Compiler for Context: Wadi_Al_Salaam_North
CREATE EXTENSION IF NOT EXISTS age;
LOAD 'age';
SELECT create_graph('wadi_al_salaam_north_graph');

-- HUB for DeceasedPerson
CREATE TABLE "Hub_DeceasedPerson" (
    "DeceasedPersonHash" CHAR(64) PRIMARY KEY,
    "VisualID" VARCHAR(50) NOT NULL,
    "LoadDate" TIMESTAMP DEFAULT NOW(),
    "RecordSource" VARCHAR(100)
);

-- SATELLITE for DeceasedPerson
CREATE TABLE "Sat_DeceasedPerson_Attributes" (
    "DeceasedPersonHash" CHAR(64) REFERENCES "Hub_DeceasedPerson"("DeceasedPersonHash"),
    "LoadDate" TIMESTAMP DEFAULT NOW(),
    "FullName_Arabic" TEXT,
    "DateOfDeath" TEXT,
    "TribeName" TEXT,
    "PlotNumber" TEXT,
    "HashDiff" CHAR(64)
);

-- HUB for FamilyPlot
CREATE TABLE "Hub_FamilyPlot" (
    "FamilyPlotHash" CHAR(64) PRIMARY KEY,
    "VisualID" VARCHAR(50) NOT NULL,
    "LoadDate" TIMESTAMP DEFAULT NOW(),
    "RecordSource" VARCHAR(100)
);

-- SATELLITE for FamilyPlot
CREATE TABLE "Sat_FamilyPlot_Attributes" (
    "FamilyPlotHash" CHAR(64) REFERENCES "Hub_FamilyPlot"("FamilyPlotHash"),
    "LoadDate" TIMESTAMP DEFAULT NOW(),
    "FamilyName" TEXT,
    "Capacity" TEXT,
    "HashDiff" CHAR(64)
);

