# =============================================
# AKKADIAN GENERATED AI SERVICE (FastAPI)
# Generated by Akkadian.Compiler v3.0
# =============================================
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from typing import List, Dict

# Initialize App
app = FastAPI(title="Akkadian Vector Service")

print('Loading Model: ...')
model_beeMDM_Knowledge = SentenceTransformer('')

class EmbeddingRequest(BaseModel):
    text: str

@app.post('/beemdm_knowledge/embed')
async def embed_beemdm_knowledge(req: EmbeddingRequest):
    embeddings = model_beeMDM_Knowledge.encode(req.text)
    return { 'vector': embeddings.tolist() }

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
